version: "3"
services:
    cement:
        image: "cement:dev"
        build:
            context: .
            dockerfile: docker/Dockerfile.dev
        hostname: cement
        stdin_open: true
        tty: true
        volumes:
            - ".:/app"
        links:
            - redis:redis
            - memcached:memcached
        environment:
            REDIS_HOST: redis
            MEMCACHED_HOST: memcached

    redis:
        image: redis:latest
        hostname: redis

    memcached:
        image: memcached:latest
        hostname: memcached
